# Generated by Django 3.0.7 on 2021-05-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
